basePath: /
definitions:
  url.ShortenRequest:
    properties:
      password:
        type: string
      url:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: a0970785699@gmail.com
    name: Leon Lin
    url: github.com/leon123858
  description: This is a sample in go tutorial for building a short URL service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Simple Short URL API Server
  version: "1.0"
paths:
  /{token}:
    get:
      consumes:
      - application/json
      description: Get the long URL for a given short URL token
      parameters:
      - description: Short URL token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to long URL
          schema:
            type: string
        "404":
          description: URL not found
          schema:
            type: string
      summary: Get long URL
      tags:
      - URLs
  /shorten:
    post:
      consumes:
      - application/json
      description: Create a new short URL for a given long URL
      parameters:
      - description: URL to be shortened
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/url.ShortenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Short URL
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create short URL
      tags:
      - URLs
swagger: "2.0"
