apiVersion: v1
kind: Secret
metadata:
  name: gke-poc-secret
type: Opaque
data:
  postgres-password: "MDAwMA==" # 0000's base64 encoding
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gke-poc-config
data:
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-poc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-poc
  template:
    metadata:
      labels:
        app: gke-poc
    spec:
      containers:
        - name: gke-poc
          image: leon1234858/gke-poc:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: gke-poc-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gke-poc-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              value: postgres-service
            - name: REDIS_HOST
              value: redis-service
---
apiVersion: v1
kind: Service
metadata:
  name: gke-poc-service
spec:
  type: LoadBalancer
  selector:
    app: gke-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gke-poc-secret
                  key: postgres-password
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis