# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install Swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
        
    - name: Generate Swagger Docs
      run: make swag
      working-directory: ./short-url
        
    - name: Run Tests
      run: make test
      working-directory: ./short-url
        
    - name: Build
      run: make build
      working-directory: ./short-url
